name: EstudoDeCaso

on:
  push:
    branches: ["dev"]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build -t $(date +%s) .